language: objective-c
osx_image: xcode10.1
env:
    - PACKAGE_MANAGER="cocoapods" TEST_PLATFORM="platform=iOS Simulator,OS=12.1,name=iPhone XR"
    - PACKAGE_MANAGER="cocoapods" TEST_PLATFORM="platform=iOS Simulator,OS=12.1,name=iPhone 7"
    - PACKAGE_MANAGER="cocoapods" TEST_PLATFORM="platform=iOS Simulator,OS=12.1,name=iPhone 8"
rvm:
    - 2.3.7
before_install:
    - gem install cocoapods -v '1.5.3'
    - gem install slather
    - gem install xcpretty -N --no-ri --no-rdoc
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
install:
    - ./.travis/install.sh
script: ./.travis/test.sh
after_success: slather
matrix:
    include:
        - env:
            - PACKAGE_MANAGER="carthage" TEST_PLATFORM="platform=iOS Simulator,OS=12.1,name=iPhone 8"
