language: objective-c
osx_image: xcode11.2

env:
  global:
    - secure: H45yyUlB0cXQrzTTcnmD3WrkCyqjUzaop2jHgmBF3bm8ue4XOcTWKDSDcAN39SG0FUeDC7GdDCtWAc3VCpLwN++5IznAnvBuZSGgxQ2lCxWMhdTtXtOWU2mivgVvs+uldS7/TuVlOjZ7inrTgetl+jgFjenwESOGIIZwn7SXpPo=

# The first dot is not a typo. It's needed to export the env variables to the current travis script
before_install: . .travis/setup.sh 

jobs:
  include:
    - name: "Test Snowplow framework [iOS]"
      script: .travis/test_framework.sh "${BUILD_DEST}" "${BUILD_PROJECT_LIB}" "${BUILD_SCHEME_LIB}"
      after_success: slather

    - name: "Test Snowplow ObjC demo app [iOS]"
      script: .travis/test_ios_demo.sh SnowplowDemo Podfile "${BUILD_DEST}" "${BUILD_WORKSPACE_OBJC_DEMO}" "${BUILD_SCHEME_OBJC_DEMO}"

    - name: "Test Snowplow Swift demo app [iOS] using Carthage"
      script: .travis/test_ios_demo.sh SnowplowSwiftCarthageDemo Cartfile "${BUILD_DEST}" "${BUILD_PROJECT_SWIFT_DEMO}" "${BUILD_SCHEME_SWIFT_DEMO}"

    - name: "Test Snowplow Swift demo app [iOS] using Cocoapods (no directive)"
      script: .travis/test_ios_demo.sh SnowplowSwiftCocoapodsDemo Podfile_simple "${BUILD_DEST}" "${BUILD_WORKSPACE_SWIFT_DEMO}" "${BUILD_SCHEME_SWIFT_DEMO}"

    - name: "Test Snowplow Swift demo app [iOS] using Cocoapods (use_frameworks! directive)"
      script: .travis/test_ios_demo.sh SnowplowSwiftCocoapodsDemo Podfile_frameworks "${BUILD_DEST}" "${BUILD_WORKSPACE_SWIFT_DEMO}" "${BUILD_SCHEME_SWIFT_DEMO}"

    - name: "Test Snowplow Swift demo app [iOS] using Cocoapods (use_modular_headers! directive)"
      script: .travis/test_ios_demo.sh SnowplowSwiftCocoapodsDemo Podfile_modular_headers "${BUILD_DEST}" "${BUILD_WORKSPACE_SWIFT_DEMO}" "${BUILD_SCHEME_SWIFT_DEMO}"
