language: objective-c
osx_image: xcode10.1
env:
    - TEST_PLATFORM="platform=iOS Simulator,OS=10.0,name=iPhone XR"
    - TEST_PLATFORM="platform=iOS Simulator,OS=11.0,name=iPhone XR"
    - TEST_PLATFORM="platform=iOS Simulator,OS=12.0,name=iPhone XR"
rvm:
    - 2.3.7
before_install:
    - gem install cocoapods -v '1.5.3'
    - gem install slather
    - gem install xcpretty -N --no-ri --no-rdoc
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
install:
    - ./.travis/install.sh
script: ./.travis/test.sh
after_success: slather
