language: objective-c
osx_image: xcode11.1
env:
    - TEST_PLATFORM="platform=iOS Simulator,OS=13.1,name=iPhone 8"
rvm:
    - 2.3.7
before_install:
    - gem install slather
    - gem install xcpretty -N --no-document
install:
    - ./.travis/install.sh
script: ./.travis/test.sh
after_success: slather
